version: "3"
services:
  node-app:
    build:
      context: .
      # the context above is to point at the directory
      # where the docker file so the build happens
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      # the stuff written in volumes are so every files added in the project
      # syncs the image ella l node_modules
      # this part should not be present in the prod compose file
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=maurice
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret

    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=maurice
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
