version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=maurice
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      # the line below is to save the mongo volume under the
      # "mongo-db" name (we got "/data/db" from the docs)
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  # the volumes listing here is because it has to be used
  # from other places.. and it has the same name as given
  # 6 lines above
  mongo-db:
